apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-09-25T10:07:55Z"
  generation: 1
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
  resourceVersion: "13548"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginx-1
  uid: 80f66097-b38b-4bd8-a294-9776c2fa1a30
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - image: gcr.io/node-app-290210/react-gke
        imagePullPolicy: Always
        name: react-gke-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-09-25T10:07:58Z"
    lastUpdateTime: "2020-09-25T10:07:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-25T10:07:55Z"
    lastUpdateTime: "2020-09-25T10:07:58Z"
    message: ReplicaSet "nginx-1-57fc6c75cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3